### ISSUE TITLE
Saily buy button doesn't show erika

### ISSUE THREAD

**Issue by mansonstein1** [Paisseon/Erika#10]
I'm on iPhone 12 15.1.1, xina 1.1.5, saily 1671024469 rootless version. Erika 1.10.1.
It never shows up when I click buy button. Tried reinstall  Erika/ reboot/ ... What else can I try? Thx

**Comment by Paisseon** [comment]
Is Saily in English language or another language? Ik that Russian users have this issue, they just need to tap the Russian equivalent of "Copy Meta" and it does the same thing

**Comment by mansonstein1** [comment]
> Is Saily in English language or another language? Ik that Russian users have this issue, they just need to tap the Russian equivalent of "Copy Meta" and it does the same thing

Yes, solved

**Comment by Paisseon** [comment]
Will try to make this automatic for other languages in next update
