### ISSUE TITLE
Lack of tweak after installation

### ISSUE THREAD

**Issue by D1mar0n** [Paisseon/Erika#12]
Hello! I have iPnone 12 Pro / iOS 14.2 / Taurine 1.1.6. Switched to this Jailbreak from Unc0ver 8.0.2. Now after installing your tweak, it is missing in the settings. Please tell me how to solve this problem? Thank you very much for your tweaks and thanks in advance for your reply.

![8D558120-5704-476C-98CD-D0282FE02C9B](https://user-images.githubusercontent.com/35725771/211230706-49ef496c-a2a5-4980-8f92-e39718f916f2.png)

**Comment by Paisseon** [comment]
There are no preferences in the latest version, it can be disabled through Choicy though

**Comment by D1mar0n** [comment]
Thanks for the answer! I do not have tweak settings for the last 3 versions! How to activate your tweak? I can't download any of the paid tweaks in Zebra or Sileo 😒

Enviado desde iPhone


Jan 10 2023 at 00:35, Lilliana ***@***.***> wrote:


Closed #12 as completed.
