### ISSUE TITLE
Tweak not working

### ISSUE THREAD

**Issue by D1mar0n** [Paisseon/Erika#13]
After installation, there is no way to activate the tweak, in Zebra / Sileo it is not possible to download anything from paid tweaks, themes or applications...

**Comment by Paisseon** [comment]
As in, the popup with buttons doesn't appear when you tap the tweak icon?

**Comment by D1mar0n** [comment]
Nothing at all! If you want I can record a video for you. Once installed, neither Sileo nor Zebra has the ability to download paid tweaks or themes.

Enviado desde iPhone


Jan 14 2023 at 4:51 pm, Lilliana ***@***.***> wrote:


As in, the popup with buttons doesn't appear when you tap the tweak icon?

**Comment by n4ngal1ce** [comment]
I face the same issues, not working on iOS 16.3.1 both on Sileo and Zebra.

**Comment by D1mar0n** [comment]
I have iOS 14.2 / iPhone 12 Pro
На Вс.26.03.2023 17:32:04, n4ngal1ce ***@***.***> написал(а):
I face the same issues, not working on iOS 16.3.1 both on Sileo and Zebra.

**Comment by Paisseon** [comment]
Which version of Erika are you using?

**Comment by D1mar0n** [comment]
1.10.3
На Чт.30.03.2023 0:39:07, Lilliana ***@***.***> написал(а):
Which version of Erika are you using?

**Comment by cobrax1** [comment]
having the same issue with ios 16.3.1

**Comment by Paisseon** [comment]
Can you guys check if Erika.dylib is included in the runtime browser of FLEXing (or similar)? Also, cobrax1, are you using rootless or rootful?

**Comment by cobrax1** [comment]
well  got it to work  actually thanks so much for tweek  , usefull  , all i needed was someone to explain to me how it works  and i had to read  the description  <3  thanks for ur work

**Comment by D1mar0n** [comment]
Thanks a lot for your help and advice. Everything is working! 👌
На Пн.10.04.2023 2:29:44, cobrax1 ***@***.***> написал(а):
well got it to work actually thanks so much for tweek , usefull , all i needed was someone to explain to me how it works and i had to read the description <3 thanks for ur work

**Comment by Mabdelwanis** [comment]
thanks alot for amazing tweak i got error tweak not found in server in selio and saily i'm on ios 15.4.1 Fugu15 rootless any help legend

**Comment by Paisseon** [comment]
> thanks alot for amazing tweak i got error tweak not found in server in selio and saily i'm on ios 15.4.1 Fugu15 rootless any help legend

This just means that the deb files aren't in the database. Although CyDown isn't set up for rootless so until it gets updated, Erika won't help with Fugu15/Dopamine
