### ISSUE TITLE
Couldn't Install on Fugu15Max

### ISSUE THREAD

**Issue by Aun-dot** [Paisseon/Erika#16]
How can i get it on iOS 15.2 Fugu15Max?

**Comment by Paisseon** [comment]
Not compatible with non-Xina rootless jailbreaks. Even if I were to add rootless for Erika, it wouldn't work on any iphoneos-arm64 tweaks due to CyDown not supporting the new architecture.

If Julio updates CyDown to have iphoneos-arm64 I'll fix Erika for it.
