### ISSUE TITLE
How to solve this problem?

### ISSUE THREAD

**Issue by kffnqtd** [Paisseon/Erika#17]
![06AB9B00-B649-4067-80D7-84BFF64DE640](https://user-images.githubusercontent.com/29828845/232925984-c6c11dbd-3415-4c00-ac50-619b21b0c0c7.jpeg)

**Comment by Paisseon** [comment]
Which tweak are you trying to download? That error means that something is wrong with locating the tweak in the database

**Comment by kffnqtd** [comment]
I try for many tweaks,free or non free. It’s show this error.

**Comment by Paisseon** [comment]
Does it show any other error before that? If it has this for a free tweak, the issue is actually in `let (data, response): (Data, URLResponse) = try await URLSession.shared.data14(for: URLRequest(url: r1URL))` which means that it should display a different error for ~5 seconds.

**Comment by kffnqtd** [comment]
Your reply remind me that maybe that was my network problem, it’s solved by use VPN connection. Thank you!
