### ISSUE TITLE
Erika doesn't work

### ISSUE THREAD

**Issue by lqr1** [Paisseon/Erika#25]
![image](https://github.com/Paisseon/Erika/assets/128184565/e322a789-e44a-4ace-b0ed-c0c71358994f)

sileo
ios 15.1
dopamine

**Comment by Paisseon** [comment]
Maybe try with a VPN? This is connection issue, not one with the tweak's client-side code.

**Comment by lqr1** [comment]
> Maybe try with a VPN? This is connection issue, not one with the tweak's client-side code.

i tried to install DLeasy tweak but when i tried to open the dleasy tweak from settings it crashes
