### ISSUE TITLE
Does not work on iOS 15

### ISSUE THREAD

**Issue by NotDarkn** [Paisseon/Erika#4]
Hi! I'm currently using a jailbroken iOS 15.1 device (Xina15, A13), and when trying to use Erika on iOS 15, it does not work. My main assumption is probably because of the Orion Runtime being only available on iOS 14, but it was worth making an issue on here too.

**Comment by Paisseon** [comment]
Known issue, I'll check it out and update when my exams are over 👍

**Comment by NotDarkn** [comment]
Edit: It seems that the Orion Runtime works fine on iOS 15, as I just saw other tweaks work with it. The other possibility is because of how the Xina jailbreak changes the Sileo name from Sileo to Sileo-preboot, so all of the identifiers are different. Oh well.

**Comment by NotDarkn** [comment]
> Known issue, I'll check it out and update when my exams are over 👍

Ah alright, thank you!

**Comment by NotDarkn** [comment]
iOS 15 support was added, closing...
