### ISSUE TITLE
Updated Erika to 1.10.1, yet does not work in Sileo

### ISSUE THREAD

**Issue by NotDarkn** [Paisseon/Erika#5]
**iPhone / iOS:** iPhone 11 Pro | iOS 15.1
**Jailbreak / Version:** XinaA15 | v1.1.4

**Describe your issue:**
Currently, I installed the new verison of Erika that supposedly added iOS 15 compatibility and fixed a lot of issues. However, when trying to use it in any versions of Sileo that support Xina, it does not work.

**Sileo used:**
- Sileo Nightly from repo.anamy.gay
- Sileo-fix from XinaA15
- Sileo-2.4 from /Sileo

**How to Reproduce:**
1. Install Erika v1.10 or above.
2. Install any of the Sileo's listed above.
3. Tap on an icon on a paid or even free tweak.

**Comment by Paisseon** [comment]
Try Saily, it doesn't work in Sileo on Xina, idk why

**Comment by NotDarkn** [comment]
> Try Saily, it doesn't work in Sileo on Xina, idk why

alright sure, i'll try it on Saily. 
i haven't used Saily due to the amount of people i've heard say it is a very buggy package manager

**Comment by NotDarkn** [comment]
> Try Saily, it doesn't work in Sileo on Xina, idk why

doesn't work in Saily either, crashes the app

**Comment by Paisseon** [comment]
Yeah there was some controversy recently since Xina made it default, but I've been using Saily pretty much since it came out with few issues

**Comment by NotDarkn** [comment]
> Yeah there was some controversy recently since Xina made it default, but I've been using Saily pretty much since it came out with few issues

Do you have any plans to re-add Sileo support or have you completely given up on it?

**Comment by Paisseon** [comment]
I don't have Xina, but if someone figures out why [this](https://github.com/Paisseon/Erika/blob/emt/Sources/Erika/Hooks/SileoHook.swift) is broken on Xina's Sileo, I can definitely add support. And it works on Sileo outside of Xina

**Comment by Paisseon** [comment]
If you have FLEXing and could check the `center` value for the `Sileo.PackageIconView` (tweak icon in the depiction) and see if it is not (46, 46) that's the only thing of which I can think

**Comment by NotDarkn** [comment]
> If you have FLEXing and could check the `center` value for the `Sileo.PackageIconView` (tweak icon in the depiction) and see if it is not (46, 46) that's the only thing of which I can think

Alright sure, give me a minute.

**Comment by NotDarkn** [comment]
> If you have FLEXing and could check the `center` value for the `Sileo.PackageIconView` (tweak icon in the depiction) and see if it is not (46, 46) that's the only thing of which I can think

Where can I find that? I have the tweak, just don't know where to find "center" or "Sileo.PackageIconView"

**Comment by Paisseon** [comment]
In the depiction of a tweak in Sileo, activate the tab bar by long-press three fingers, then pick "select" and tap on the tweak icon, it should say "Sileo.PackageIconView", then tap "views" and the circled i next to the highlighted Sileo.PackageIconView row, `@property CGPoint center` should be in the shortcuts section

**Comment by NotDarkn** [comment]
> In the depiction of a tweak in Sileo, activate the tab bar by long-press three fingers, then pick "select" and tap on the tweak icon, it should say "Sileo.PackageIconView", then tap "views" and the circled i next to the highlighted Sileo.PackageIconView row, `@property CGPoint center` should be in the shortcuts section

I activated it, however trying to press an icon on Sileo doesn't do anything. Using select on icons like the home screen works, but on Sileo, it doesn't.

**Comment by Paisseon** [comment]
Close the flex bar and activate it from within the Sileo app

**Comment by NotDarkn** [comment]
> Close the flex bar and activate it from within the Sileo app

I can't activate it within the Sileo app, I can in apps like Enmity and Spotify. But not Sileo.

**Comment by NotDarkn** [comment]
Here:

https://user-images.githubusercontent.com/73033672/208726150-56b5c0d3-bd95-49ec-915c-2d4732b6304e.mp4

**Comment by Paisseon** [comment]
Not disabled through Choicy?

**Comment by NotDarkn** [comment]
> Not disabled through Choicy?

I don't have Choicy installed.

**Comment by Paisseon** [comment]
I wonder if there's a UIWindow issue with Xina/Sileo that causes this, since Erika and FLEXing both create UIWindow and present as key... anyway, Violyn should work so use that ig :p

**Comment by NotDarkn** [comment]
> I wonder if there's a UIWindow issue with Xina/Sileo that causes this, since Erika and FLEXing both create UIWindow and present as key... anyway, Violyn should work so use that ig :p

alright sure, I'll try Violyn in a minute.

**Comment by NotDarkn** [comment]
where can I install Violyn? I can't find it on either CyDown's repo nor yours.

**Comment by NotDarkn** [comment]
nevermind, found it!

**Comment by NotDarkn** [comment]
what am I suppose to do with Violyn?

**Comment by Paisseon** [comment]
Either use the search function, tap on the bundle ID you want, then tap Download, or use the download function and enter the bundle ID and version of the tweak, which can be seen at the bottom of a Sileo depiction

**Comment by NotDarkn** [comment]
> Either use the search function, tap on the bundle ID you want, then tap Download, or use the download function and enter the bundle ID and version of the tweak, which can be seen at the bottom of a Sileo depiction

alright, give me a minute.

**Comment by NotDarkn** [comment]
> Either use the search function, tap on the bundle ID you want, then tap Download, or use the download function and enter the bundle ID and version of the tweak, which can be seen at the bottom of a Sileo depiction

it won't show up upon using the search function, i'mma just go the simply way out and use the sileo-fix.ipa that Xina provides rather than the nightly channel.

**Comment by NotDarkn** [comment]
> Either use the search function, tap on the bundle ID you want, then tap Download, or use the download function and enter the bundle ID and version of the tweak, which can be seen at the bottom of a Sileo depiction

odd, using FLEXing in either Sileo Nightly or Sileo-fix.ipa (Xina GitHub) does not work or get detected by Violyn. closest I get is either junesiphone.sileonbanner_v0.1 which is 4.0kb, and com.modmyi.bubblesileon_v1 which is 38.3mb. i know both of these aren't Sileo however as Sileo should have the com.coolstar Bundle ID at the beginning, so yeah they don't show up.

**Comment by Paisseon** [comment]
Sorry, I meant that in Sileo you can see the bundle ID and version at the bottom of depictions, and in Violyn you can use those information to get the download. Violyn doesn't include Sileo itself

**Comment by NotDarkn** [comment]
> Sorry, I meant that in Sileo you can see the bundle ID and version at the bottom of depictions, and in Violyn you can use those information to get the download. Violyn doesn't include Sileo itself

ah alright, i thought you were asking for me to use Violyn to download Sileo and try to use FLEXing on that instead lol

**Comment by Paisseon** [comment]
Yeah I can see how it sounded like that :p

**Comment by NotDarkn** [comment]
> Yeah I can see how it sounded like that :p

Well, are you still going to add support back for Sileo x XinaA15 or are you going to redirect users to use Violyn or Saily?

**Comment by Paisseon** [comment]
I'll add support for Sileo × Xina when someone using the jailbreak figures out why it isn't working. Until then, I have 0 chance of fixing it.
