### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by kidiron08** [Paisseon/Erika#6]
Gives me this error
![2507F082-CD84-40DD-B607-6FC66B946E57](https://user-images.githubusercontent.com/120617336/208254383-ceee2723-cbf1-4d02-90ee-727c76027497.png)

**Comment by Paisseon** [comment]
Are you using 1.10 or 1.10.1? Also, what iOS version and jailbreak are you using, and which package manager?

**Comment by kidiron08** [comment]
I’m using 1.10 15.7.1 sileo palera1n

**Comment by kidiron08** [comment]
And it won’t let me install 1.10.1

**Comment by Paisseon** [comment]
> And it won’t let me install 1.10.1

What error does it give?
