### ISSUE TITLE
Upon trying to install the .deb Erika downloaded, it fails to install

### ISSUE THREAD

**Issue by NotDarkn** [Paisseon/Erika#8]
**iPhone / iOS:** iPhone 11 Pro | iOS 15.1
**Jailbreak / Version:** XinaA15 | v1.1.4

**Describe your issue:**
After using Erika on Saily and downloading the .deb, upon installation of the .deb it will not work. 
Upon trying to use the .deb in Sileo, it does nothing.
Upon trying to use the .deb in Saily, it gives a "Failed to verify package" error.
Upon trying to use the .deb in Filza, it doesn't give the option to "Install"

**Package Managers Used:**
Sileo (Nightly Channel) - 2.4+20221215 - repo.anamy.gay
Saily - 1671024469 - .com/SailyTeam/Saily

**How to Reproduce:**
1. Install Sileo or Saily
2. Install Erika from Paisseon
3. Open Saily and use Erika on any paid/free tweak
4. Select "Erika" and download the tweak
5. After downloading, tap "Get Zappy" and install the .deb.
6. Share it with either Sileo or Saily and it won't work.
7. Try installing it with Filza and it will not give you the option to install.

**Video of issue:**

https://user-images.githubusercontent.com/73033672/208257075-ce1f45ed-9932-4686-8950-8fc43d1434de.mp4

**Comment by Paisseon** [comment]
Does it have the same issue if you try to install any deb? As long as the debs show up without an error message they should be fine

**Comment by NotDarkn** [comment]
Yeah nevermind it wasn’t an issue with Erika, it was with Filza. At the time, I was using version 3.9.7 which didn’t officially support Xina rootless, cause of that it didn’t give me the option to install IN Filza. However 4.0.0 came out so things like the install button now shows up on .deb’s. To summarize: Filza issue, not Xina. Fixed now too.
