### ISSUE TITLE
Erika Buy Option Crashes Saily on Xina15

### ISSUE THREAD

**Issue by Egco2811** [Paisseon/Erika#9]
I am using Xina15 jailbreak on iOS15.0 and iPhone 11. When I try to use Erika with Saily it crashes and does not work. I have tried using both rootless and rooted Saily and tried both the .ipa and .deb files the problem still occured.

**Comment by Paisseon** [comment]
Did the issue fix itself or...?

**Comment by Egco2811** [comment]
yeah I cleared data of saily from apps manager and it worked

**Comment by mansonstein1** [comment]
> 

Hi. What saily version are you using? My doesn't  show erika after cliking buy button. Xina 1.1.5.
